<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="apiChainingHttpMethodInDiffrentClass.CreateUserTest">
        <methods>
          <include name="createUser"/>
        </methods>
      </class> <!-- apiChainingHttpMethodInDiffrentClass.CreateUserTest -->
      <class name="apiChainingHttpMethodInDiffrentClass.DeleteUserTest">
        <methods>
          <include name="deleteUser" invocation-numbers="0"/>
        </methods>
      </class> <!-- apiChainingHttpMethodInDiffrentClass.DeleteUserTest -->
      <class name="apiChainingHttpMethodInDiffrentClass.UpdateUserTest">
        <methods>
          <include name="updateUser"/>
        </methods>
      </class> <!-- apiChainingHttpMethodInDiffrentClass.UpdateUserTest -->
      <class name="apiChainingHttpMethodInDiffrentClass.GetUserTest">
        <methods>
          <include name="getUser"/>
        </methods>
      </class> <!-- apiChainingHttpMethodInDiffrentClass.GetUserTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
